- name: Validar proceso Connect Direct
  shell: |
      if [ $(ps -eo args | grep -v grep | egrep -w "cdpmgr|cdstatm" | wc -l) -eq 2 ]
      then
      echo ACTIVO
      elif [ $(ps -eo args | grep -v grep | egrep -w "cdpmgr|cdstatm" | wc -l) -eq 0 ]
      then
      echo INACTIVO
      elif [ $(ps -eo args | grep -v grep | egrep -w "cdpmgr|cdstatm" | wc -l) -eq 1 ]
      then
      echo VALIDACION_FALLIDA
      fi
  register: statuscd

- name: Resultado de la validacion del proceso Connect Direct
  debug:
    msg:
       - "Connect Direct ........{{ statuscd.stdout }}"
  when: statuscd.stdout == "ACTIVO" or statuscd.stdout == "INACTIVO"

- name: Resultado del validacion de procesos Connect Direct
  fail:
    msg:
       - "Connect Direct ........{{ statuscm.stdout }}"
       - "No todos los procesos estan ACTIVOS"
       - "Escalar con el Ã¡rea de InfraUnix"
  when: statuscd.stdout == "VALIDACION_FALLIDA"
