- name: Alta proceso CapacityAgent
  become: yes
  become_user: patrol
  become_method: su
  become_exe: sudo su -
  shell: |
      /usr/adm/best1_default/bgs/scripts/best1agent_stop -b /usr/adm/best1_default
      /etc/bgs/SD/bgssd.exe -d /etc/bgs/SD -k
      /usr/adm/best1_default/bgs/bin/MrStat -b /usr/adm/best1_default -k
      sleep 10

- name: Validar proceso CapacityAgent
  shell: |
      if [ $(ps -eo args | grep -v grep | egrep "bgsagent|bgscollect|bgssd" | wc -l) -eq 3 ]
      then
      echo ACTIVO
      elif [ $(ps -eo args | grep -v grep | egrep "bgsagent|bgscollect|bgssd" | wc -l) -eq 1 ]
      then
      echo ACTIVACION_FALLIDA
      elif [ $(ps -eo args | grep -v grep | egrep "bgsagent|bgscollect|bgssd" | wc -l) -eq 2 ]
      then
      echo ACTIVACION_FALLIDA
      fi
  register: statusca
  
- name: Resultado de la alta del proceso CapacityAgent
  debug:
    msg:
       - "CapacityAgent ........{{ statuscm.stdout }}"
  when: statusca.stdout == "ACTIVO"
  
- name: Resultado de la alta del proceso CapacityAgent
  fail:
    msg:
       - "CapacityAgent ........{{ statuscm.stdout }}"
       - "No se pudo ACTIVAR de forma correcta"
       - "Escalar con el Ã¡rea de RTMonitoreo"
  when: statusca.stdout == "ACTIVACION_FALLIDA"
