- name: Alta proceso Control-M_Agent
  become: yes
  shell: |
      if [ "$(ls -d /controlm)" = "/controlm" ]
      then
      /controlm/ag700/ctm/scripts/start-ag -u ag700 -p ALL
      elif [ "$(ls -d /ctrlmagt)" = "/ctrlmagt" ]
      then
      /ctrlmagt/ctm/scripts/start-ag -u ag700 -p ALL
      fi

- name: Validar proceso Control-M_Agent
  shell: |
      if [ $(ps -eo args | grep -v grep | egrep "ctmag$|ctmat$|ctmatw" | wc -l) -eq 3 ]
      then
      echo ACTIVO
      elif [ $(ps -eo args | grep -v grep | egrep "ctmag$|ctmat$|ctmatw" | wc -l) -eq 1 ]
      then
      echo ACTIVACION_FALLIDA
      elif [ $(ps -eo args | grep -v grep | egrep "ctmag$|ctmat$|ctmatw" | wc -l) -eq 2 ]
      then
      echo ACTIVACION_FALLIDA
      fi
  register: statuscm
  
- name: Resultado de la alta del proceso Control-M_Agent
  debug:
    msg:
       - "Control-M_Agent ........{{ statuscm.stdout }}"
  when: statuscm.stdout == "ACTIVO"
  
- name: Resultado de la alta del proceso Control-M_Agent
  fail:
    msg:
       - "Control-M_Agent ........{{ statuscm.stdout }}"
       - "No todos los procesos de Control-M_Agent estan ACTIVOS"
       - "Escalar con el Ã¡rea de gestion de Mallas Control-M"
  when: statuscm.stdout == "ACTIVACION_FALLIDA"
