- name: Validar proceso Control-M_Agent
  shell: |
      if [ $(ps -eo args | grep -v grep | egrep "ctmag$|ctmat$|ctmatw" | wc -l) -eq 3 ]
      then
      echo ACTIVO
      elif [ $(ps -eo args | grep -v grep | egrep "ctmag$|ctmat$|ctmatw" | wc -l) -eq 0 ]
      then
      echo INACTIVO
      elif [ $(ps -eo args | grep -v grep | egrep "ctmag$|ctmat$|ctmatw" | wc -l) -eq 1 ]
      then
      echo VALIDACION_FALLIDA
      elif [ $(ps -eo args | grep -v grep | egrep "ctmag$|ctmat$|ctmatw" | wc -l) -eq 2 ]
      then
      echo VALIDACION_FALLIDA
      fi
  register: statuscm
  
- name: Resultado de la validacion del proceso Control-M_Agent
  debug:
    msg:
       - "Control-M_Agent ........{{ statuscm.stdout }}"
  when: statuscm.stdout == "ACTIVO" or statuscm.stdout == "INACTIVO"
  
- name: Resultado de la validacion del proceso Control-M_Agent
  fail:
    msg:
       - "Control-M_Agent ........{{ statuscm.stdout }}"
       - "No todos los procesos estan ACTIVOS"
       - "Escalar con el Ã¡rea de gestion de Mallas Control-M"
  when: statuscm.stdout == "VALIDACION_FALLIDA"
