- name: Baja proceso Dimension
  become: yes
  shell: |
        /opt/dimensions/[1-9][1-9].[1-9]/cm/prog/dmshutdown 2>/dev/null
        sleep 15
  
- name: Validacion procesos Dimension
  shell: |
      if [ $(ps -eo args | grep -v grep | grep "dimension" | wc -l) -eq 0 ]
      then
      echo INACTIVO
      elif [ $(ps -eo args | grep -v grep | grep "dimension" | wc -l) -eq 1 ]
      then
      echo INACTIVACION_FALLIDA
      elif [ $(ps -eo args | grep -v grep | grep "dimension" | wc -l) -eq 2 ]
      then
      echo INACTIVACION_FALLIDA
      fi
  register: statusdm
  
- name: Resultado de la alta del proceso Dimension
  debug:
    msg:
       - "Dimension ........{{ statusdm.stdout }}"
  when: statusdm.stdout == "INACTIVO"
  
- name: Resultado de la alta del proceso Dimension
  fail:
    msg:
       - "Dimensions ........{{ statusdm.stdout }}"
       - "No todos los procesos de Dimension estan INACTIVOS"
       - "Escalar con el Ã¡rea de gestion de Dimensions"
  when: statusdm.stdout == "INACTIVACION_FALLIDA"
