- name: Validacion - DIMENSION
  become: yes
  shell: |
      if [ $(ps -eo args | grep -v grep | grep "dimension" | wc -l) -eq 3 ]
      then
      echo ACTIVO
      elif [ $(ps -eo args | grep -v grep | grep "dimension" | wc -l) -eq 0 ]
      then
      echo INACTIVO
      elif [ $(ps -eo args | grep -v grep | grep "dimension" | wc -l) -eq 1 ]
      then
      echo VALIDACION_FALLIDA
      elif [ $(ps -eo args | grep -v grep | grep "dimension" | wc -l) -eq 2 ]
      then
      echo VALIDACION_FALLIDA
      fi
  register: statusca
  
- name: Resultado de la validacion de DIMENSION
  debug:
    msg:
       - "Dimension ........{{ statusca.stdout }}"
  when: statusca.stdout == "ACTIVO" or statusca.stdout == "INACTIVO"
  
- name: Resultado de la validacion de DIMENSION
  fail:
    msg:
       - "Dimensions ........{{ statusca.stdout }}"
       - "No todos los procesos de Dimension estan ACTIVOS"
       - "Escalar con el Ã¡rea de gestion de Dimensions"
  when: statusca.stdout == "VALIDACION_FALLIDA"
