- name: Validar proceso PatrolAgent
  shell: |
      if [ $(ps -eo args | grep -v grep | grep -qw PatrolAgent | wc -l) -eq 1 ]
      then
      echo ACTIVO
      elif [ $(ps -eo args | grep -v grep | grep -qw PatrolAgent | wc -l) -eq 0 ]
      then
      echo INACTIVO
      fi      
  register: statuspa

- name: Resultado de la validacion del proceso PatrolAgent
  debug:
    msg:
       - "PatrolAgent ........{{ statuspa.stdout }}"
  when: statuspa.stdout == "ACTIVO"

- name: Resultado de la validacion del proceso PatrolAgent
  debug:
    msg:
       - "PatrolAgent ........{{ statuspa.stdout }}"
  when: statuspa.stdout == "INACTIVO"
